# name: dev environment deploy

# on:
#   push:
#     branches:
#       - "dev"
# jobs:
#   CI:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Setup Terraform
#         uses:
#   CD:
