name: Terraform dev destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      

jobs:
  terraform-destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # assume role을 위한 arn
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
        working-directory: environment/dev
      - name: Terraform Destroy
        run: terraform destroy -var-file="dev.tfvars"
        working-directory: environment/dev
