# name: dev environment deploy

# on:
#   push:
#     branches:
#       - "dev"
#     paths:
#       - "**.java"
#     paths-ignore:
#       - "**.md"

# jobs:
#   CI:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Setup Terraform
#         uses:
#   CD:
