name: Terraform dev plan

on:
  # 수동 실행 포함
  workflow_dispatch: 
  push:
    # dev branch의 경우에만 push
    branches:
      - "dev"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # assume role을 위한 arn
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1 # Required
      - name: Set Working Dir 
        run: |
          if ["${{ github.ref }}" == "refs/head/dev"]; then
            echo "WORK_DIR=environment/dev" >> $GITHUB_ENV
          else 
            echo "none"
          fi
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORK_DIR }}
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ env.WORK_DIR }}
      - name: Terraform Plan
        id: tf-plan
        working-directory: ${{ env.WORK_DIR }}
        run: |
          export exitcode=0
          terraform plan -var-file="environment/dev/dev.tfvars" -detailed-exitcode -no-color -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi
        